# -*- coding: utf-8 -*-
"""Canada_per_Capita.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FlTPWC-8T8TNBuSY-yqCcfoCMbMtydvU
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Read csv
df = pd.read_csv("canada_per_capita_income.csv")
print(df)

# Scatter plot
plt.scatter(df['year'], df['per capita income (US$)'], color='red', marker='+')
plt.xlabel("Year")
plt.ylabel("Per Capita Income (US$)")
plt.title("Canada Per Capita Income Prediction")
plt.show()

# Model training
reg = LinearRegression()
reg.fit(df[['year']], df['per capita income (US$)'])

# Prediction for 2020
income_2020 = reg.predict([[2020]])
print("Predicted income for year 2020:", income_2020[0])

# Coefficient and intercept
print("Coefficient:", reg.coef_[0])
print("Intercept:", reg.intercept_)